### ISSUE TITLE
Body already used

### ISSUE THREAD

**Issue by xxwallacexx** [wobsoriano/elysia-autoroutes#10]
packages
"elysia": "0.7",
"elysia-autoroutes": "^0.4.0"

```
export default (app: ElysiaApp) => app
  .post("/", async (ctx) => {
    try {
      const payload = await ctx.request.text()
    }catch(e){
    }
})
```
It return error
error: Body already used
      at processTicksAndRejections (:55:76)

**Comment by kravetsone** [comment]
Body already parsed on `onParse` life-cycle hook. It's not elysia-autoroutes error

**Comment by wobsoriano** [comment]
Thanks @kravetsone! Closing this.
