### ISSUE TITLE
Compatibility with Elysia 0.7

### ISSUE THREAD

**Issue by lyorb** [wobsoriano/elysia-autoroutes#6]
After updating Elysia to version 0.7
I get this error message: `No overload matches this call`
For this line: `.use(autoroutes({ routesDir: "./routes" }))`

**Comment by shuvro111** [comment]
Same here. I can't get rid of that whatsoever. 😞

**Comment by wobsoriano** [comment]
Just merged a bug PR and will update for 0.7 compat

**Comment by wobsoriano** [comment]
Should be fixed on the next release (v0.4.0)

**Comment by wobsoriano** [comment]
Release v0.4.0. Feel free to reopen anytime!

**Comment by lyorb** [comment]
@wobsoriano I've updated the library to 0.4.0, but I get this error : 

```
 Elysia is running at http://localhost:3006
       ...this.config,
         prefix: ""
      });
      instance.store = this.store;
      const isSchema = typeof schemaOrRun === "object";
      const sandbox = (isSchema ? run : schemaOrRun)(instance);
                ^
TypeError: (isSchema ? run : schemaOrRun) is not a function. (In '(isSchema ? run : schemaOrRun)(instance)', '(isSchema ? run : schemaOrRun)' is undefined)
      at group
```
